language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
env:
  - DJANGO=1.5.5
  - DJANGO=1.6.8
  - DJANGO=1.7.1

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=1.7.1
install:
  - pip install .
  - pip install Django==$DJANGO --use-mirrors
  - pip install pytest pytest-pep8 pytest-flakes django-pytest --use-mirrors
  - pip install coveralls --use-mirrors
script:
  coverage run --source=stdimage runtests.py
after_success:
  coveralls
