language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.2.7
  - DJANGO=1.3.1
  - DJANGO=1.4
  - DJANGO=1.5.5
  - DJANGO=1.6.1
script:
  - cd tests
  - python bootstrap.py
  - bin/buildout
  - bin/test